################################################################
## Unused automations
################################################################

- id: notify_camera_pictures_telegram
  alias: 'Notify camera pictures using Telegram'
  initial_state: 'on'
  trigger:
   - platform: time
     minutes: '/2'
     seconds: 00
  action:
    - service: notify.telegram
      data_template:
        message: "Check camera."
        data:
          photo:
            - url: !secret porch_camera_image_url
              caption: "Test"

## Automate Christmas Lights
- alias: Turn Christmas Lights On At Sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: switch.wemoswitch
- alias: Turn Christmas Lights Off At Midnight
  trigger:
    platform: time
    after: '23:30:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.wemoswitch

- alias: 'Switch turned on when nobody is home v1'
  condition:
    condition: state
    entity_id: input_select.abodestatus
    state: 'away'
  trigger:
    - platform: state
      entity_id:
        - group.all_switches
      to: 'on'
  action:
    - service: notify.pushbullet
      data_template:
        message: >
          {% for entity in states.group.all_switches.attributes.entity_id %}
            {%- if is_state(entity, 'on') %}
              {{ states[entity.split('.')[0]][entity.split('.')[1]].name }}
            {%- endif %}
          {%- endfor %}
        title: "Switch turned on"
        target: device/myiPhone

- alias: 'Switch turned on when nobody is home v2'
  condition:
    condition: state
    entity_id: input_select.abodestatus
    state: 'away'
  trigger:
    - platform: state
      entity_id:
        - group.all_switches
      to: 'on'
  action:
    - service: notify.pushbullet
      data_template:
        message: >
          {% for entity in states.group.all_switches.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first and loop.last %}
              {{ states[entity.split('.')[0]][entity.split('.')[1]].name }} is on.
            {% elif loop.length == length(states.group.all_switches.attributes.entity_id) %}
              {{ "All switches are on." if loop.last }}
            {% else %}
              {%- if loop.first %}{% elif loop.last %} & {% else %}, {% endif -%}
              {{ states[entity.split('.')[0]][entity.split('.')[1]].name }}{{ " are on" if loop.last }}
            {%- endif -%}
          {% else %}
            All switches are off.
          {% endfor %}
        title: "Switch turned on"
        target: device/myiPhone
- alias: 'Change Lifx color'
  trigger:
   - platform: time
     minutes: '/1'
     seconds: 00
  action:
     service: ifttt.trigger
     data_template: {"event":"lifxcolor", "value1":"{{ '{:02x}{:02x}{:02x}'.format(range(0, 255) | random, range(0, 255) | random, range(0, 255) | random) }}"}
#################################################################
## Unused Sensors
#################################################################
