homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.2.0/24
        - 131.96.253.0/24
  external_url: !secret external_url
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 322
  name: Home
  temperature_unit: F
  time_zone: America/New_York
  unit_system: imperial
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config/downloads
    - /tmp
    - /config/downloads/camera/

default_config:
stream:

influxdb:
  api_version: 2
  ssl: false
  host: 192.168.2.113
  port: 8086
  organization: homeassistant
  bucket: homeassistant
  token: !secret influxdb_token
  tags:
    source: HA
  tags_attributes:
    - friendly_name
    - device_class
  default_measurement: units

python_script:

zone:
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 200
    icon: mdi:home
  - name: Buckhead
    latitude: !secret latitude_buckhead
    longitude: !secret longitude_buckhead
    radius: 200
    icon: mdi:school
  - name: Downtown
    latitude: !secret latitude_downtown
    longitude: !secret longitude_downtown
    radius: 200
    icon: mdi:school

light:
  - platform: mqtt
    name: "GE Kitchen Lights"
    state_topic: "smartthings/GE Dimmer Switch/switch"
    command_topic: "smartthings/GE Dimmer Switch/switch"
    payload_on: "on"
    payload_off: "off"
    brightness_state_topic: "smartthings/GE Dimmer Switch/level"
    brightness_command_topic: "smartthings/GE Dimmer Switch/level"
    brightness_scale: 99
    brightness_value_template: '{{ value }}'
    retain: true
    optimistic: false
    qos: 0
  - platform: group
    name: Living Room Lights
    entities:
      - light.living_room_1
      - light.living_room_2
      - light.living_room_3
      - light.living_room_4
  - platform: group
    name: Kids Room Lights
    entities:
      - light.wb4_d_2
      - light.wb4_d_3
      - light.wb4_d
  - platform: group
    name: Master Lights
    entities:
      - light.master_1
      - light.master_2
      - light.master_3

aarlo:
  username: !secret arlo_user
  password: !secret arlo_password

alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
  - platform: manual
    name: HASS Alarm
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

shell_command:
  image_classify: bash /config/shell_scripts/image_classification.sh "{{camera}}"
  facebox: bash /config/shell_scripts/facebox.sh "{{camera}}"
  delete_unifi: curl http://192.168.2.113:8086/query -d db=unifi -d q='DELETE WHERE time < now() - 5h'

rest_command:
  youtube:
    url: 'http://192.168.2.252:8001/api/v2/applications/111299001912'
    method: post
  netflix:
    url: 'http://192.168.2.252:8001/ws/apps/Netflix'
    method: post
  plex:
    url: 'http://192.168.2.252:8001/api/v2/applications/kIciSQlYEM.plex'
    method: post
  restart_pihole_study:
    url: !secret pihole_study_restart
    method: post
    headers:
      X-API-Key: !secret portainer_api_key
  restart_pihole_syn:
    url: !secret pihole_syn_restart
    method: post
    headers:
      X-API-Key: !secret portainer_api_key

media_extractor:

alexa:
  smart_home:
    filter:
      include_entities:
        - light.living_room_lights
        - light.master_lights
        - input_boolean.abodeupdate
        - light.gateway_light_34ce00813670
        - light.kitchen_lights
        - light.lifx5
        - switch.driveway
        - switch.wemoporch
        - script.tv_youtube_on
      include_domains:
        - cover
    entity_config:
      light.gateway_light_34ce00813670:
        name: Gateway Light
        description: Xiaomi Gateway Light
      script.tv_youtube_on:
        name: Youtube
        description: Youtube on

google_assistant:
  project_id: !secret google_project_id
  service_account: !include HASSGoogAssist.json
  expose_by_default: false
  entity_config:
    light.living_room_lights:
      expose: true
      room: living room
    light.master_lights:
      expose: true
      room: master bedroom
    switch.driveway:
      expose: true
      room: driveway
    switch.wemoporch:
      expose: true
      name: Porch Lights
      room: porch
    light.kitchen_lights:
      expose: true
      room: kitchen
    light.kids_room_lights:
      expose: true
      room: kids room
    light.lifx5:
      expose: true
      room: garage
    switch.wemoinsight:
      expose: true
      name: Wemo Insight
      room: office
    camera.porch:
      expose: true
      room: porch
    camera.patio:
      expose: true
      room: patio
    camera.driveway:
      expose: true
      room: driveway
    camera.backyard:
      expose: true
      room: backyard
    cover.garagedoor:
      expose: true
      room: garage

homekit:
  filter:
    include_entities:
      - alarm_control_panel.aarlo_arlohome
      - alarm_control_panel.abode_alarm
      - cover.garagedoor
      - light.living_room_lights
      - light.kids_room_lights
      - light.lifx5
      - light.kitchen_lights
      - light.master_lights
      - switch.driveway
      - binary_sensor.water_leak_sensor_158d0001d77800
      - binary_sensor.water_leak_sensor_158d00027b0db6
      - binary_sensor.water_leak_sensor_158d0001bb788c
      - camera.garage

downloader:
  download_dir: downloads

http:
  ip_ban_enabled: true
  login_attempts_threshold: 1
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/24
    - 192.168.2.0/24
    - 127.0.0.1
    - ::1
    - 172.17.0.3

amcrest:
  - host: 192.168.2.26
    username: admin
    password: !secret amcrest_password

ffmpeg:

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'
  - platform: local_file
    name: worldtime
    file_path: /config/downloads/worldtime/worldtime.png
  - platform: local_file
    name: Driveway TF
    file_path: /config/downloads/camera/driveway_latest.jpg
  - platform: local_file
    name: Porch TF
    file_path: /config/downloads/camera/porch_latest.jpg
  - platform: local_file
    name: Patio TF
    file_path: /config/downloads/camera/patio_latest.jpg
  - platform: local_file
    name: Backyard TF
    file_path: /config/downloads/camera/backyard_latest.jpg
  - platform: generic
    still_image_url: !secret meteogram_url
    name: Meteogram
  - platform: ffmpeg
    input: !secret wyzecam_rtsp_url
    name: Garage
  - platform: ffmpeg
    input: !secret amcrest_ip_cam_url
    name: Kitchen

image_processing:
  - platform: tensorflow
    confidence: 75
    scan_interval: 10000
    source:
      - entity_id: camera.patio
    file_out:
      - "/config/downloads/camera/{{ camera_entity.split('.')[1] }}_latest.jpg"
    model:
      graph: /config/tensorflow/models/efficientdet_d1_coco17_tpu-32/
      categories:
        - person
  - platform: tensorflow
    confidence: 75
    scan_interval: 10000
    source:
      - entity_id: camera.backyard
      - entity_id: camera.driveway
      - entity_id: camera.porch
    file_out:
      - "/config/downloads/camera/{{ camera_entity.split('.')[1] }}_latest.jpg"
    model:
      graph: /config/tensorflow/models/efficientdet_d1_coco17_tpu-32/
      categories:
        - category: person
          area:
            top: 0.20
        - bus
        - category: truck
          area:
            bottom: 0.70
            right: 0.20
        - category: car
          area:
            bottom: 0.70
            right: 0.20

media_player:
  - platform: androidtv
    host: 192.168.2.172
    name: "ShieldTVPro"
    device_class: androidtv
  - platform: androidtv
    host: 192.168.2.28
    name: "ShieldTV"
    device_class: androidtv
    adb_server_ip: 192.168.2.233
    apps:
      com.google.android.tvlauncher: "Home"
      com.google.android.youtube.tv: "Youtube"
      com.amazon.amazonvideo.livingroom: "Amazon Prime Video"
      com.plexapp.android: "Plex"
      com.netflix.ninja: "Netflix"
      com.google.android.tv: "Live Channels"
      org.xbmc.kodi: "Kodi"
      live.aiplex.software: "ThopTV"
      com.mxtech.videoplayer.ad: "MXPlayer"
      com.vectorunit.red: "RipTide"
  - platform: androidtv
    name: FTV Master
    host: 192.168.2.180
    device_class: firetv
    adb_server_ip: 192.168.2.233
    apps:
      com.amazon.amazonvideo.livingroom: "Amazon Prime Video"
      com.plexapp.android: "Plex"
      com.netflix.ninja: "Netflix"
      com.google.android.tv: "Live Channels"
      org.xbmc.kodi: "Kodi"
      live.aiplex.software: "ThopTV"
      com.amazon.tv.launcher: Home
      com.synology.dsvideo: "DS Video"
      com.mxtech.videoplayer.ad: "MXPlayer"
      com.amazon.firetv.youtube: "Youtube"

geofency:

speedtestdotnet:

telegram_bot:
  platform: polling
  api_key: !secret telegram_key
  allowed_chat_ids:
    - !secret telegram_chatID_Alok

pi_hole:
  - host: 192.168.2.14
    name: Pi Hole Kids
    api_key: !secret pi_hole_kids
  - host: 192.168.2.114
    name: Pi Hole Syn
    api_key: !secret pi_hole_synology

notify:
  - name: telegram
    platform: telegram
    api_key: !secret telegram_key
    chat_id: !secret telegram_chatID_Alok
  - platform: group
    name: iOS
    services:
      - service: mobile_app_alokiphone
      - service: mobile_app_rashmiiphone12
  - platform: group
    name: ios_abode_updates
    services:
      - service: mobile_app_alokiphone
        data:
          title: 'Enable Abode updates?'
          data:
            push:
              badge: 0
              category: "abode_updates"
  - platform: group
    name: ios_home_automation
    services:
      - service: mobile_app_alokiphone
        data:
          title: 'Enable Home automation?'
          data:
            push:
              badge: 0
              category: "home_automation"
  - platform: nfandroidtv
    name: Shield
    host: 192.168.2.28
  - platform: nfandroidtv
    name: AFTVMaster
    host: 192.168.2.180
  - platform: command_line
    name: 'Echo Dot'
    command: "/config/shell_scripts/alexa_wrapper.sh -d 'Echo Dot Gen2'"

logger:
  default: error
  logs:
    homeassistant.components.image_processing: critical
    homeassistant.components.camera.generic: critical
    homeassistant.components.media_player: critical
    homeassistant.components.telegram_bot: critical
    homeassistant.components.onvif: info
    pychromecast.socket_client: critical
    aiohttp.access: critical
    aiounifi.api: critical
    aiohttp.server: critical
    haffmpeg.core: critical
    homeassistant.core: critical
    pywemo.ouimeaux_device: critical
    pywemo.ssdp: critical
    homeassistant.helpers.entity: critical
    homeassistant.components.http.ban: warning
    homeassistant.components.python_script: warning

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /config/tts
    time_memory: 300

device_tracker:
  - platform: composite
    name: Alok Composite Temp
    time_as: device_or_local
    entity_id:
      - device_tracker.alokiphone
      - device_tracker.alokphone_alokphone_2
      - device_tracker.alokiphone_3
      - device_tracker.life360_alok_saboo
      - device_tracker.alok_geofency

dialogflow:

intent_script: !include intent_script.yaml
ios: !include ios.yaml
alert: !include alert.yaml
automation: !include automations.yaml
cover: !include cover.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
switch: !include switches.yaml
binary_sensor: !include binary_sensor.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_button: !include input_button.yaml
input_number: !include input_number.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
frontend: !include frontend.yaml
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
lovelace: !include lovelace.yaml
