sensor:
  - platform: ring
    monitored_conditions:
      - last_activity
      - last_ding
      - last_motion

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion
